Array ( 
 [actionName] => Block user 
 [name] => Block User on Fridays 
 [systemUserSelect] => 2 
 [controllerStatus] => Controller on 
 [amountOfPoints] => 
 [repeatEach] => eachWekk 
 [timeSPCTHidden] => 
 [startDate] => 2013-12-16 
 [endDate] => 2014-03-02 
 [timeATHidden] => 
 [startTime] => 00:00 
 [endTime] => 23:55 
 [repeatFri] => 1 ) 
Array ( 
 [actionName] => Block user 
 [name] => Block user first friday in a month 
 [systemUserSelect] => 3 
 [controllerStatus] => Controller on 
 [amountOfPoints] => 
 [repeatEach] => primo 
 [timeSPCTHidden] => 
 [startDate] => 2013-12-16 
 [endDate] => 2014-04-30 
 [timeATHidden] => 
 [startTime] => 00:00 
 [endTime] => 23:00 
 [specDay] => on ) 
Array ( 
 [actionName] => Block user 
 [name] => Block user in week 42 
 [systemUserSelect] => 1 
 [controllerStatus] => Controller on 
 [amountOfPoints] => 
 [repeatEach] => sWeek 
 [weekNo] => 42 
 [timeSPCTHidden] => 
 [startDate] => 
 [endDate] => 
 [timeATHidden] => 
 [startTime] => 00:00 
 [endTime] => 23:55 
 [repeatMon] => 1 
 [repeatTue] => 1 
 [repeatWed] => 1 
 [repeatThu] => 1 
 [repeatFri] => 1 
 [repeatSat] => 1 
 [repeatSun] => 1 ) 
Array ( 
 [actionName] => Block user 
 [name] => Block user from 
 [systemUserSelect] => 5 
 [controllerStatus] => Controller on 
 [amountOfPoints] => 
 [repeatEach] => noRepeat 
 [timeSPCTHidden] => 2013-12-22 00:00 
 [startDate] => 
 [endDate] => 
 [timeATHidden] => 
 [startTime] => 
 [endTime] => ) 
Array ( 
 [actionName] => Set maximum of point 
 [name] => Set maximum of points 
 [systemUserSelect] => 3 
 [controllerStatus] => Controller on 
 [amountOfPoints] => 1000 
 [repeatEach] => eachWekk 
 [timeSPCTHidden] => 2013-12-16 09:55 
 [startDate] => 
 [endDate] => 
 [timeATHidden] => 
 [startTime] => 
 [endTime] => ) 
Array ( 
 [actionName] => Access controller 
 [name] => User can access Tv on Saturday 
 [systemUserSelect] => 4 
 [controllerName] => 1234 
 [controllerStatus] => Controller on 
 [amountOfPoints] => 
 [repeatEach] => eachWekk 
 [timeSPCTHidden] => 
 [startDate] => 2013-12-18 
 [endDate] => 2013-12-26 
 [timeATHidden] => 
 [startTime] => 00:00 
 [endTime] => 23:55 
 [repeatSat] => 1 ) 
Array ( 
 [actionName] => Cannot access controller 
 [name] => User cannot access Wii after christmas 
 [systemUserSelect] => 4 
 [controllerName] => 123 
 [controllerStatus] => Controller on 
 [amountOfPoints] => 
 [repeatEach] => noRepeat 
 [timeSPCTHidden] => 
 [startDate] => 2013-12-25 
 [endDate] => 2013-12-25 
 [timeATHidden] => 
 [startTime] => 00:00 
 [endTime] => 00:00 ) 
Array ( 
 [actionName] => noAccessIf 
 [name] => Cannot access Wii if Playstation 
 [controllerName] => 123 
 [controllerNameIf] => 124 
 [controllerStatus] => Controller on 
 [amountOfPoints] => 
 [repeatEach] => eachWekk 
 [timeSPCTHidden] => 
 [startDate] => 
 [endDate] => 
 [timeATHidden] => 
 [startTime] => 
 [endTime] => )